---

- name: set google-cloud-sdk repo
  copy:
    src: google-cloud-sdk.repo
    dest: /etc/yum.repos.d/google-cloud-sdk.repo
    mode: 0644

- name: install rpms
  yum:
    name="{{ item }}"
    state=latest
    update_cache=yes
  with_items:
    - google-cloud-sdk
